In [2]:
import numpy as np
import pandas as pd

In [3]:
df=pd.read_csv(r"C:\Users\91955\Desktop\Health\dailyActivity_merged.csv")
df

,Id,ActivityDate,TotalSteps,TotalDistance,TrackerDistance,LoggedActivitiesDistance,VeryActiveDistance,ModeratelyActiveDistance,LightActiveDistance,SedentaryActiveDistance,VeryActiveMinutes,FairlyActiveMinutes,LightlyActiveMinutes,SedentaryMinutes,Calories
0,1503960366,04-12-2016,13162,8.500000,8.500000,0.0,1.88,0.55,6.06,0.00,25,13,328,728,1985
1,1503960366,4/13/2016,10735,6.970000,6.970000,0.0,1.57,0.69,4.71,0.00,21,19,217,776,1797
2,1503960366,4/14/2016,10460,6.740000,6.740000,0.0,2.44,0.40,3.91,0.00,30,11,181,1218,1776
3,1503960366,4/15/2016,9762,6.280000,6.280000,0.0,2.14,1.26,2.83,0.00,29,34,209,726,1745
4,1503960366,4/16/2016,12669,8.160000,8.160000,0.0,2.71,0.41,5.04,0.00,36,10,221,773,1863
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
935,8877689391,05-08-2016,10686,8.110000,8.110000,0.0,1.08,0.20,6.80,0.00,17,4,245,1174,2847
936,8877689391,05-09-2016,20226,18.250000,18.250000,0.0,11.10,0.80,6.24,0.05,73,19,217,1131,3710
937,8877689391,05-10-2016,10733,8.150000,8.150000,0.0,1.35,0.46,6.28,0.00,18,11,224,1187,2832
938,8877689391,05-11-2016,21420,19.559999,19.559999,0.0,13.22,0.41,5.89,0.00,88,12,213,1127,3832
939,8877689391,05-12-2016,8064,6.120000,6.120000,0.0,1.82,0.04,4.25,0.00,23,1,137,770,1849

In [4]:
df.dropna()

,Id,ActivityDate,TotalSteps,TotalDistance,TrackerDistance,LoggedActivitiesDistance,VeryActiveDistance,ModeratelyActiveDistance,LightActiveDistance,SedentaryActiveDistance,VeryActiveMinutes,FairlyActiveMinutes,LightlyActiveMinutes,SedentaryMinutes,Calories
0,1503960366,04-12-2016,13162,8.500000,8.500000,0.0,1.88,0.55,6.06,0.00,25,13,328,728,1985
1,1503960366,4/13/2016,10735,6.970000,6.970000,0.0,1.57,0.69,4.71,0.00,21,19,217,776,1797
2,1503960366,4/14/2016,10460,6.740000,6.740000,0.0,2.44,0.40,3.91,0.00,30,11,181,1218,1776
3,1503960366,4/15/2016,9762,6.280000,6.280000,0.0,2.14,1.26,2.83,0.00,29,34,209,726,1745
4,1503960366,4/16/2016,12669,8.160000,8.160000,0.0,2.71,0.41,5.04,0.00,36,10,221,773,1863
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
935,8877689391,05-08-2016,10686,8.110000,8.110000,0.0,1.08,0.20,6.80,0.00,17,4,245,1174,2847
936,8877689391,05-09-2016,20226,18.250000,18.250000,0.0,11.10,0.80,6.24,0.05,73,19,217,1131,3710
937,8877689391,05-10-2016,10733,8.150000,8.150000,0.0,1.35,0.46,6.28,0.00,18,11,224,1187,2832
938,8877689391,05-11-2016,21420,19.559999,19.559999,0.0,13.22,0.41,5.89,0.00,88,12,213,1127,3832
939,8877689391,05-12-2016,8064,6.120000,6.120000,0.0,1.82,0.04,4.25,0.00,23,1,137,770,1849

In [5]:
df.drop_duplicates()

,Id,ActivityDate,TotalSteps,TotalDistance,TrackerDistance,LoggedActivitiesDistance,VeryActiveDistance,ModeratelyActiveDistance,LightActiveDistance,SedentaryActiveDistance,VeryActiveMinutes,FairlyActiveMinutes,LightlyActiveMinutes,SedentaryMinutes,Calories
0,1503960366,04-12-2016,13162,8.500000,8.500000,0.0,1.88,0.55,6.06,0.00,25,13,328,728,1985
1,1503960366,4/13/2016,10735,6.970000,6.970000,0.0,1.57,0.69,4.71,0.00,21,19,217,776,1797
2,1503960366,4/14/2016,10460,6.740000,6.740000,0.0,2.44,0.40,3.91,0.00,30,11,181,1218,1776
3,1503960366,4/15/2016,9762,6.280000,6.280000,0.0,2.14,1.26,2.83,0.00,29,34,209,726,1745
4,1503960366,4/16/2016,12669,8.160000,8.160000,0.0,2.71,0.41,5.04,0.00,36,10,221,773,1863
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
935,8877689391,05-08-2016,10686,8.110000,8.110000,0.0,1.08,0.20,6.80,0.00,17,4,245,1174,2847
936,8877689391,05-09-2016,20226,18.250000,18.250000,0.0,11.10,0.80,6.24,0.05,73,19,217,1131,3710
937,8877689391,05-10-2016,10733,8.150000,8.150000,0.0,1.35,0.46,6.28,0.00,18,11,224,1187,2832
938,8877689391,05-11-2016,21420,19.559999,19.559999,0.0,13.22,0.41,5.89,0.00,88,12,213,1127,3832
939,8877689391,05-12-2016,8064,6.120000,6.120000,0.0,1.82,0.04,4.25,0.00,23,1,137,770,1849

In [6]:
df.count()

Id                          940
ActivityDate                940
TotalSteps                  940
TotalDistance               940
TrackerDistance             940
LoggedActivitiesDistance    940
VeryActiveDistance          940
ModeratelyActiveDistance    940
LightActiveDistance         940
SedentaryActiveDistance     940
VeryActiveMinutes           940
FairlyActiveMinutes         940
LightlyActiveMinutes        940
SedentaryMinutes            940
Calories                    940
dtype: int64

In [7]:
#Generate basic statistics for all numeric columns(count, non missing values, min value, max value, mean, median, quartile values)

In [8]:
df[["Id","ActivityDate","TotalSteps","TotalDistance","TrackerDistance","LoggedActivitiesDistance","VeryActiveDistance","ModeratelyActiveDistance","LightActiveDistance","SedentaryActiveDistance","VeryActiveMinutes","FairlyActiveMinutes","LightlyActiveMinutes","SedentaryMinutes","Calories"]].count()

Id                          940
ActivityDate                940
TotalSteps                  940
TotalDistance               940
TrackerDistance             940
LoggedActivitiesDistance    940
VeryActiveDistance          940
ModeratelyActiveDistance    940
LightActiveDistance         940
SedentaryActiveDistance     940
VeryActiveMinutes           940
FairlyActiveMinutes         940
LightlyActiveMinutes        940
SedentaryMinutes            940
Calories                    940
dtype: int64

In [9]:
df[["Id","ActivityDate","TotalSteps","TotalDistance","TrackerDistance","LoggedActivitiesDistance","VeryActiveDistance","ModeratelyActiveDistance","LightActiveDistance","SedentaryActiveDistance","VeryActiveMinutes","FairlyActiveMinutes","LightlyActiveMinutes","SedentaryMinutes","Calories"]].mean()

C:\Users\91955\AppData\Local\Temp\ipykernel_6628\2613547842.py:1: FutureWarning: The default value of numeric_only in DataFrame.mean is deprecated. In a future version, it will default to False. In addition, specifying 'numeric_only=None' is deprecated. Select only valid columns or specify the value of numeric_only to silence this warning.
  df[["Id","ActivityDate","TotalSteps","TotalDistance","TrackerDistance","LoggedActivitiesDistance","VeryActiveDistance","ModeratelyActiveDistance","LightActiveDistance","SedentaryActiveDistance","VeryActiveMinutes","FairlyActiveMinutes","LightlyActiveMinutes","SedentaryMinutes","Calories"]].mean()

Id                          4.855407e+09
TotalSteps                  7.637911e+03
TotalDistance               5.489702e+00
TrackerDistance             5.475351e+00
LoggedActivitiesDistance    1.081709e-01
VeryActiveDistance          1.502681e+00
ModeratelyActiveDistance    5.675426e-01
LightActiveDistance         3.340819e+00
SedentaryActiveDistance     1.606383e-03
VeryActiveMinutes           2.116489e+01
FairlyActiveMinutes         1.356489e+01
LightlyActiveMinutes        1.928128e+02
SedentaryMinutes            9.912106e+02
Calories                    2.303610e+03
dtype: float64

In [10]:
df["Id"].mean()

4855407369.332978

In [11]:
df["Id"].min()

1503960366

In [12]:
df["Id"].max()

8877689391

In [13]:
df["Id"].median()

4445114986.0

In [14]:
df["Id"].quantile()

4445114986.0

In [15]:
df[["Id","ActivityDate","TotalSteps","TotalDistance","TrackerDistance","LoggedActivitiesDistance","VeryActiveDistance","ModeratelyActiveDistance","LightActiveDistance","SedentaryActiveDistance","VeryActiveMinutes","FairlyActiveMinutes","LightlyActiveMinutes","SedentaryMinutes","Calories"]].min()

Id                          1503960366
ActivityDate                04-12-2016
TotalSteps                           0
TotalDistance                      0.0
TrackerDistance                    0.0
LoggedActivitiesDistance           0.0
VeryActiveDistance                 0.0
ModeratelyActiveDistance           0.0
LightActiveDistance                0.0
SedentaryActiveDistance            0.0
VeryActiveMinutes                    0
FairlyActiveMinutes                  0
LightlyActiveMinutes                 0
SedentaryMinutes                     0
Calories                             0
dtype: object

In [16]:
df[["Id","ActivityDate","TotalSteps","TotalDistance","TrackerDistance","LoggedActivitiesDistance","VeryActiveDistance","ModeratelyActiveDistance","LightActiveDistance","SedentaryActiveDistance","VeryActiveMinutes","FairlyActiveMinutes","LightlyActiveMinutes","SedentaryMinutes","Calories"]].max()

Id                          8877689391
ActivityDate                 4/30/2016
TotalSteps                       36019
TotalDistance                28.030001
TrackerDistance              28.030001
LoggedActivitiesDistance      4.942142
VeryActiveDistance               21.92
ModeratelyActiveDistance          6.48
LightActiveDistance              10.71
SedentaryActiveDistance           0.11
VeryActiveMinutes                  210
FairlyActiveMinutes                143
LightlyActiveMinutes               518
SedentaryMinutes                  1440
Calories                          4900
dtype: object

In [17]:
df[["Id","ActivityDate","TotalSteps","TotalDistance","TrackerDistance","LoggedActivitiesDistance","VeryActiveDistance","ModeratelyActiveDistance","LightActiveDistance","SedentaryActiveDistance","VeryActiveMinutes","FairlyActiveMinutes","LightlyActiveMinutes","SedentaryMinutes","Calories"]].median()

C:\Users\91955\AppData\Local\Temp\ipykernel_6628\2024848501.py:1: FutureWarning: The default value of numeric_only in DataFrame.median is deprecated. In a future version, it will default to False. In addition, specifying 'numeric_only=None' is deprecated. Select only valid columns or specify the value of numeric_only to silence this warning.
  df[["Id","ActivityDate","TotalSteps","TotalDistance","TrackerDistance","LoggedActivitiesDistance","VeryActiveDistance","ModeratelyActiveDistance","LightActiveDistance","SedentaryActiveDistance","VeryActiveMinutes","FairlyActiveMinutes","LightlyActiveMinutes","SedentaryMinutes","Calories"]].median()

Id                          4.445115e+09
TotalSteps                  7.405500e+03
TotalDistance               5.245000e+00
TrackerDistance             5.245000e+00
LoggedActivitiesDistance    0.000000e+00
VeryActiveDistance          2.100000e-01
ModeratelyActiveDistance    2.400000e-01
LightActiveDistance         3.365000e+00
SedentaryActiveDistance     0.000000e+00
VeryActiveMinutes           4.000000e+00
FairlyActiveMinutes         6.000000e+00
LightlyActiveMinutes        1.990000e+02
SedentaryMinutes            1.057500e+03
Calories                    2.134000e+03
dtype: float64

In [18]:
df[["Id","ActivityDate","TotalSteps","TotalDistance","TrackerDistance","LoggedActivitiesDistance","VeryActiveDistance","ModeratelyActiveDistance","LightActiveDistance","SedentaryActiveDistance","VeryActiveMinutes","FairlyActiveMinutes","LightlyActiveMinutes","SedentaryMinutes","Calories"]].quantile()

C:\Users\91955\AppData\Local\Temp\ipykernel_6628\2068560598.py:1: FutureWarning: The default value of numeric_only in DataFrame.quantile is deprecated. In a future version, it will default to False. Select only valid columns or specify the value of numeric_only to silence this warning.
  df[["Id","ActivityDate","TotalSteps","TotalDistance","TrackerDistance","LoggedActivitiesDistance","VeryActiveDistance","ModeratelyActiveDistance","LightActiveDistance","SedentaryActiveDistance","VeryActiveMinutes","FairlyActiveMinutes","LightlyActiveMinutes","SedentaryMinutes","Calories"]].quantile()

Id                          4.445115e+09
TotalSteps                  7.405500e+03
TotalDistance               5.245000e+00
TrackerDistance             5.245000e+00
LoggedActivitiesDistance    0.000000e+00
VeryActiveDistance          2.100000e-01
ModeratelyActiveDistance    2.400000e-01
LightActiveDistance         3.365000e+00
SedentaryActiveDistance     0.000000e+00
VeryActiveMinutes           4.000000e+00
FairlyActiveMinutes         6.000000e+00
LightlyActiveMinutes        1.990000e+02
SedentaryMinutes            1.057500e+03
Calories                    2.134000e+03
Name: 0.5, dtype: float64